name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Run Cypress tests
        run: npm run cypress:run # Ensure this script is defined in your package.json
